### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by EulogiaKoine** [EulogiaKoine/koine#1]
# Tasks

대충 개발 예정인 것들 올리는 이슈게시판

**Comment by EulogiaKoine** [comment]
## version 0.2
2023-05-06
<br>

### initialization 방식 개선

- [x] 1. import 규약 재작성
- [ ] 2. 규약에 맞춰 Data flow 다이어그램 작성
- [x] 3. 규약에 맞춰 코드 작성
- [x] 4. 직접 호출 시 require 및 모듈 캐싱(자동이면 스킵) 설정
- [x] 5. 모듈 분할 및 최대한 import없이도 기능하긴 하도록 재구조화; 없으면 불가능할 경우 예외 처리
- [x] 6. 통합 및 테스트
- [x] 7. README 작성 후 릴리즈

```typescript
before:
    koine.init() 으로 통합되긴 했지만 포맷이 통일되지 않음
    심지어 세부사항은 내부 패키지를 직접 호출해서 다른 형식으로 init해줘야하는 문제도 있음. 심각. 생산성 저하 예고.

goal:
    require('koine')(global)로 최초에 전역 전달
    koine.init( "packageName.moduleName"[, string req2[, ...]]) 형태로 기존 사용

result:
    koine.PackageManager.init(...)
    koine.lib.packageName.moduleName 으로 속성 직접 호출 가능
```

**Comment by EulogiaKoine** [comment]
## version 0.3
2023-05-06

- [x] README 작성 및 커밋

### extension.Array.findLast~ 추가
생각보다 불편했다...

- [x] findLast()
- [x] findLastIndex()

<br>


### extension.Date 추가
&nbsp;java.text.SimpleDateFormat을 이용, 간편한 문자열 형식화/파싱 지원. 날로 먹는 것 같아서 좋... 아니 좀 찔리지만 편하니까.

- [x] Date.prototype.format(): 날짜 문자열 형식화
- [x] Date.fromFormat(str[, pattern]): 형식화된 문자열로부터 Date객체 생성

**Comment by EulogiaKoine** [comment]
## version 0.4
<p>2023-05-06</p>
<p>+koine.reinforce</p>

- [ ] README 작성 및 커밋

<br>


### 0. klib, kpack 설치
전역에 넘겨받은 _global 객체로 koine 대신

```javascript
koine.PackageManager -> kpack
koine.lib -> klib
```

으로 라이브러리 인터페이스명을 확실히 보장함으로써 모듈/패키지 간 소통을 가능하게 하고 접근성을 향상시킨다.

- [x] 코드 적용
- [x] README 수정

<br><br>


### 1. 모듈 index.js 반환 양식 변경

모듈 간 소통 강화 수단 및 독립된 모듈 스코프<sup>클로저</sup> 사용 강제를 통한 모듈 안정성 보장. 모듈은 index.js에서 모듈이 제공하는 기능/클래스<sup>function</sup>를 반환하는 함수를 export해야 한다는 양식 추가.

- [x] README - How to Develop? 규약 추가
- [x] Module 클래스 수정
- [x] Package 클래스 수정
- [x] 기존 모듈들 수정
- [x] 테스트


<br><br>

### 2. reinforce.setTimeout2

- [ ] 규약 작성
- [ ] 다이어그램
- [ ] syncroninzer: 싱글 스레딩용 모듈
- [ ] setTimeout
- [ ] clearTimeout
- [ ] setInterval
- [ ] clearInterval


#### 기존 RhinoJS setTimeout/setInterval: 매 실행마다 스레드를 생성. 이로 인한 문제점:

1. 스레드 과다 생성으로 인한 속도 감소(가끔 과부화) 
2. 멀티 스레딩의 장점을 기본적으로 장착하게 됨
3. 컴파일해도 그대로 남아있어서 비상 정지가 곤란함


#### 개선 방향:

1. 새로운 스레드 생성X
2. 기존 JS 환경과 동일하게 싱글 스레드로 처리되도록 변환
3. 컴파일 시 자동 소멸

#### 추가점:
1. id 저장 까먹더라도 비상 정지가 가능하도록 timeout/interval id[]를 static 속성으로 저장
2. (1)번 응용, static allStop()

<br>


### 3. send

- [ ] 규약 작성
- [ ] flowchart
- [ ] async_sender: 비동기 전송 모듈
- [ ] send

&nbsp;기존 Api.replyRoom / bot.send 혹은 (replier|msg).reply는 필자 기기 기준 15~30ms정도를 연산에 소요한다. 중간에 껴서 처리하기엔 매우 비효율적이며, 결과값에 다른 코드가 영향을 전혀 받지도 않는다. 따라서 비동기적으로 빼버리는 게 최선.
<br>

&nbsp;사용법은 동일하다.
